### ISSUE TITLE
Woodcut replay file not found when running WoodCutReplayTest

### ISSUE THREAD

**Issue by llvieira** [Terasology/TestReplayModule#5]
After downloading this module, I ran `WoodCutReplayTest.java` and an exception popped out saying that no replay found with Woodcut title. Then, I'm debugging it to catch this issue.

The first thing I realized, is that the method `getSavedGameOrRecording(Path saveOrRecordingPath)` put all the recorded file paths found into a `SortedMap` where the key is the last modified time of each corresponding `manifest.json`, however as the last modified time seems just the same for both **Woodcut** and **Example**, then the last recorded file path replaces the other one.

So I added a blank space to the Woodcut manifest file and as its last modified time was changed, I was able to ran it till the end. It is just a workaround though.

In a more illustrative way, the following is what happens...

Putting **Woodcut** file path into the map:
![captura de tela de 2018-09-26 23-41-13](https://user-images.githubusercontent.com/26657147/46122046-1182e100-c1ed-11e8-8ee0-3f5258cd26e6.png)

Putting **Example** file path into the map (it replaced the woodcut file path, because as you can see it has the same key value):
![captura de tela de 2018-09-26 23-42-47](https://user-images.githubusercontent.com/26657147/46122048-15aefe80-c1ed-11e8-95c3-dac81654d669.png)

The exception:
![captura de tela de 2018-09-26 23-44-36](https://user-images.githubusercontent.com/26657147/46122053-1a73b280-c1ed-11e8-9928-fec8bc7674ef.png)

After the addition of a blank space to woodcut manifest file (now, we have a different key value):
![captura de tela de 2018-09-27 00-18-15](https://user-images.githubusercontent.com/26657147/46122265-28760300-c1ee-11e8-8be8-52bed23ff7c7.png)

I'll try to figure out this problem, but if someone already have any idea, let me know it. :+1:

**Comment by llvieira** [comment]
I think this problem is somehow related to Linux systems. I ran it in two different Linux machines and I got the same error, however it worked fine with Windows.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
